name = "openpentacle"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "openpentacle-db"
database_id = "31cf074f-81eb-4231-81e4-89723e4bcf67"
migrations_dir = "src/lib/server/db/migrations"
